# Generated by Django 5.1.3 on 2025-01-21 09:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conges_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat a Duree Indeterminee'), ('CDD', 'Contrat a Duree Determinee'), ('STAGE', 'Stage'), ('SPECIFIC', 'Autre specifique')], max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_quoridien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('probation_period_end', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employe', models.CharField(max_length=50)),
                ('prenom_employe', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image_employee', models.URLField(blank=True)),
                ('adresse_employe', models.CharField(max_length=40)),
                ('date_embauche', models.DateField()),
                ('anciennite', models.IntegerField()),
                ('date_recrutement', models.DateField()),
                ('training', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('requirments', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=50)),
                ('applicant_name', models.CharField(max_length=40)),
                ('date_interview', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField()),
                ('interview_location', models.CharField(max_length=40)),
                ('notes', models.TextField()),
                ('condidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.condidate')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='ContratHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('tempsSt', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.contrats')),
            ],
        ),
        migrations.AddField(
            model_name='contrats',
            name='Employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeur'),
        ),
        migrations.CreateModel(
            name='Conges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('type_conge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges', to='myapp.conges_type')),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeur')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('annuel_conge_balance', models.IntegerField(default=0)),
                ('malade_conge_balance', models.IntegerField(default=0)),
                ('materninty_conge_balance', models.IntegerField(default=0)),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.conges_type')),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeur')),
            ],
        ),
        migrations.CreateModel(
            name='absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeur')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField()),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('objectifs_archieved', models.TextField()),
                ('strenghts', models.TextField()),
                ('areas_for_improvement', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeur')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Salarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_salaire', models.CharField(max_length=50)),
                ('monthely_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_date', models.DateField()),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeur')),
            ],
        ),
        migrations.AddField(
            model_name='employeur',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.services'),
        ),
    ]
